version: '3.6'

services:
  frontend:
    restart: always
    image: "quay.io/openware/baseapp:2.6.24"
    ports:
      - "3002:3000"
    volumes:
      - ../config/frontend/env.js:/usr/share/nginx/html/config/env.js
    labels:
      - "traefik.http.routers.frontend-civicforge.rule=Host(`www.app.local`) && PathPrefix(`/`)"
      - "traefik.enable=true"
      - "traefik.http.services.frontend-civicforge.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend-civicforge.entrypoints=web"

  tower:
    restart: always
    image: "quay.io/openware/tower:2.6.24"
    volumes:
      - ../config/frontend/tower.js:/home/app/env.js
    labels:
      - "traefik.http.routers.tower-civicforge.rule=Host(`www.app.local`) && PathPrefix(`/tower`)"
      - "traefik.enable=true"
      - "traefik.http.services.tower-civicforge.loadbalancer.server.port=8080"
      - "traefik.http.routers.tower-civicforge.entrypoints=web"
