version: '3.6'

services:
  gateway:
    restart: always
    image: envoyproxy/envoy:v1.10.0
    ports:
      - "10001:8099"
    volumes:
      - ../config/gateway:/etc/envoy/
    command: /usr/local/bin/envoy -l info -c /etc/envoy/envoy.yaml
    labels:
      - "traefik.http.routers.gateway-civicforge.rule=Host(`www.app.local`) && PathPrefix(`/api`,`/admin`,`/assets/`)"
      - "traefik.enable=true"
      - "traefik.http.services.gateway-civicforge.loadbalancer.server.port=8099"
      - "traefik.http.routers.gateway-civicforge.entrypoints=web"
